spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/task_db
    username: admin
    password: 123
    driver-class-name: org.postgresql.Driver
    hibernate:
      dll-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    secretKey: secret
    expiration: 36000000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
